// DOM SELECTORS
const btn1 = document.getElementById("button1")
const btn2 = document.getElementById("button2")
const btn3 = document.getElementById("button3")
const btn4 = document.getElementById("button4")
const btn5 = document.getElementById("button5")
const btn6 = document.getElementById("button6")
const btn7 = document.getElementById("button7")
const btn8 = document.getElementById("button8")
const btn9 = document.getElementById("button9")
// EVENT LISTENERS
btn1.addEventListener("click", (e) => {})
btn2.addEventListener("click", (e) => {})
btn3.addEventListener("click", (e) => {})
btn4.addEventListener("click", (e) => {})
btn5.addEventListener("click", (e) => {})
btn6.addEventListener("click", (e) => {})
btn7.addEventListener("click", (e) => {})
btn8.addEventListener("click", (e) => {})
btn9.addEventListener("click", (e) => {})
